export const mockStories = [
  {
    by: 'PaulHoule',
    descendants: 0,
    id: 39589187,
    score: 1,
    time: 1709551691,
    title: 'Smallest wildcat of the Atlantic Forest faces enormous threats',
    type: 'story',
    url: 'https://news.mongabay.com/2024/02/smallest-wildcat-of-the-atlantic-forest-faces-enormous-threats/',
  },
  {
    by: 'mattboyle',
    descendants: 0,
    id: 39589183,
    score: 1,
    time: 1709551650,
    title: 'How I keep myself alive using Golang',
    type: 'story',
    url: 'https://www.bytesizego.com/blog/keeping-alive-with-go',
  },
  {
    by: '_overment',
    descendants: 0,
    id: 39589172,
    score: 1,
    time: 1709551552,
    title: 'Between Copilots and Autonomous Agents',
    type: 'story',
    url: 'https://www.techsistence.com/p/thinking-about-the-usefulness-of',
  },
  {
    by: 'flxflx',
    descendants: 1,
    id: 39589109,
    kids: [39589110],
    score: 1,
    time: 1709550977,
    title: 'CTOs of Azure, AMD, and Intel Discussing "Confidential AI" at OC3 Conference',
    type: 'story',
    url: 'https://www.oc3.dev/speakers-and-talks#the-status-quo-and-potential-of-confidential-ai',
  },
  {
    by: 'ColinWright',
    descendants: 0,
    id: 39589102,
    score: 2,
    time: 1709550903,
    title: 'The Theorist Who Sees Math in Art, Music and Writing',
    type: 'story',
    url: 'https://www.quantamagazine.org/the-theorist-who-sees-math-in-art-music-and-writing-20240112/',
  },
  {
    by: 'heraju',
    descendants: 1,
    id: 39589100,
    kids: [39589113],
    score: 1,
    text: 'Traditional SaaS reporting often involves a manual, time-consuming process of selecting and organizing data to generate insights. However, the logical way of building reports is just a fraction of what we can truly show our users. Imagine having a database with 150 tables – the sheer number of combinations for joins is staggering.<p>Using the formula for combinations, we can calculate the total number of potential joins:\nC(n, k) = n! &#x2F; [k! * (n - k)!]\nFor our database scenario:\nn = 150 (total number of tables)\nk = 2 (number of tables selected for each join)<p>Plugging these values into the formula:\nC(150, 2) = 150! &#x2F; [2! * (150 - 2)!]\nAfter computation, we find there are 11,175 possible combinations of joins for our database.<p>This complexity highlights why AI-powered reporting is superior. AI algorithms can swiftly navigate through vast amounts of data, identifying patterns and generating meaningful insights without being bogged down by manual processes. With AI, we can uncover correlations, trends, and outliers that might have otherwise remained hidden.',
    time: 1709550885,
    title: "Is SaaS reporting enough in today's data-driven world?",
    type: 'story',
  },
  {
    by: 'sergefdrv',
    descendants: 1,
    id: 39589089,
    kids: [39589090],
    score: 1,
    time: 1709550760,
    title: 'On Implementation of Distributed Protocols',
    type: 'story',
    url: 'https://replica-io.dev/blog/2024/03/04/on-implementation-of-distributed-prtocols',
  },
  {
    by: 'ingve',
    descendants: 0,
    id: 39589065,
    score: 1,
    time: 1709550484,
    title: 'Incorrect Stack Exchange Answers Make Me Angry',
    type: 'story',
    url: 'https://1f6042.blogspot.com/2024/03/incorrect-stack-exchange-answers-make.html',
  },
  {
    by: 'goranmoomin',
    descendants: 0,
    id: 39589051,
    score: 1,
    time: 1709550305,
    title: 'I built a self-serving advertisement solution for myself',
    type: 'story',
    url: 'https://fangpenlin.com/posts/2023/03/01/why-i-built-a-self-serving-advertisement-solution/',
  },
  {
    by: 'pain_perdu',
    descendants: 1,
    id: 39589033,
    kids: [39589190],
    score: 1,
    time: 1709550120,
    title: 'Humane Serves 40 Page Cease and Desist to Open-Source Project',
    type: 'story',
    url: 'https://twitter.com/kodjima33/status/1764472814353183199',
  },
  {
    by: 'usui',
    descendants: 0,
    id: 39589032,
    score: 1,
    time: 1709550118,
    title: 'The Winner Takes It All',
    type: 'story',
    url: 'https://deprogrammaticaipsum.com/the-winner-takes-it-all/',
  },
  {
    by: 'soapsommelier',
    descendants: 0,
    id: 39589021,
    score: 1,
    time: 1709549988,
    title: 'SimplyNews PH – AI agent generated podcast of the latest on Product Hunt',
    type: 'story',
    url: 'https://simply-product-hunt.podbean.com/',
  },
  {
    by: 'todsacerdoti',
    descendants: 0,
    id: 39589018,
    score: 1,
    time: 1709549932,
    title: 'Quiz: A tool for rapid OpenZFS development',
    type: 'story',
    url: 'https://despairlabs.com/blog/posts/2024-03-04-quiz-rapid-openzfs-development/',
  },
  {
    by: 'mouzogu',
    descendants: 0,
    id: 39589005,
    score: 2,
    time: 1709549718,
    title: 'Bitcoin passes new all-time high in euros as price reaches $65K',
    type: 'story',
    url: 'https://cointelegraph.com/news/bitcoin-new-ath-euros-price-65k',
  },
  {
    by: 'mrhashem',
    descendants: 1,
    id: 39588997,
    kids: [39588998],
    score: 6,
    time: 1709549620,
    title: 'A Linux Optimizer Script.',
    type: 'story',
    url: 'https://github.com/hawshemi/Linux-Optimizer',
  },
  {
    by: 'teleforce',
    descendants: 0,
    id: 39588977,
    score: 2,
    time: 1709549376,
    title: 'A windowed graph Fourier transform',
    type: 'story',
    url: 'https://ieeexplore.ieee.org/abstract/document/6319640',
  },
  {
    by: 'todsacerdoti',
    descendants: 0,
    id: 39588964,
    score: 2,
    time: 1709549227,
    title: 'On Pausing Containers – how we built, and why we deprecated, our container paus',
    type: 'story',
    url: 'https://metalbear.co/blog/on-pausing-containers-how-we-built-and-why-we-deprecated-our-container-pause-feature/',
  },
  {
    by: 'paulcjh',
    descendants: 0,
    id: 39588951,
    score: 1,
    time: 1709549070,
    title: 'AI Optimised for Dental Diagnostics',
    type: 'story',
    url: 'https://dentistry.co.uk/2024/03/04/ai-optimised-for-dental-diagnostics/',
  },
  {
    by: 'awalias',
    descendants: 0,
    id: 39588919,
    score: 1,
    time: 1709548722,
    title: 'PostgREST Aggregate Functions',
    type: 'story',
    url: 'https://supabase.com/blog/postgrest-aggregate-functions',
  },
  {
    by: 'weatherlight',
    descendants: 3,
    id: 39588905,
    kids: [39589116, 39589111, 39589086],
    score: 8,
    time: 1709548639,
    title: 'Household Sex (In the Roman Empire)',
    type: 'story',
    url: 'https://roman-empire.net/society/household-sex/',
  },
];
