/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as ArticuloIndexImport } from './routes/articulo/index'
import { Route as ArticuloArticuloIDImport } from './routes/articulo/$articuloID'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ArticuloIndexRoute = ArticuloIndexImport.update({
  path: '/articulo/',
  getParentRoute: () => rootRoute,
} as any)

const ArticuloArticuloIDRoute = ArticuloArticuloIDImport.update({
  path: '/articulo/$articuloID',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/articulo/$articuloID': {
      id: '/articulo/$articuloID'
      path: '/articulo/$articuloID'
      fullPath: '/articulo/$articuloID'
      preLoaderRoute: typeof ArticuloArticuloIDImport
      parentRoute: typeof rootRoute
    }
    '/articulo/': {
      id: '/articulo/'
      path: '/articulo'
      fullPath: '/articulo'
      preLoaderRoute: typeof ArticuloIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AboutRoute,
  ArticuloArticuloIDRoute,
  ArticuloIndexRoute,
})

/* prettier-ignore-end */
